# Generated by Django 3.0.3 on 2022-01-11 05:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tyre_stock', '0004_auto_20210424_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_order_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('tyre_number', models.TextField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('fitment_position', models.TextField(blank=True, max_length=200, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT'), ('KOTAK', 'KOTAK'), ('SBI', 'SBI'), ('HDFC', 'HDFC')], max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_done', models.BooleanField(default=False)),
                ('tyre_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyre_stock.tyre_stockmodel')),
            ],
        ),
    ]
