# Generated by Django 3.0.3 on 2022-01-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_order_model_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order_model',
            name='mail_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
