# Generated by Django 3.0.3 on 2022-01-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_order_model_mail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order_model',
            name='mail_id',
            field=models.CharField(max_length=254),
        ),
    ]
