# Generated by Django 3.0.3 on 2022-01-11 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20220111_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order_model',
            name='mail_id',
            field=models.CharField(error_messages={'validators': 'Please enter correct email id'}, max_length=254, validators=[django.core.validators.RegexValidator(regex='([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\\.[A-Z|a-z]{2,})+')]),
        ),
        migrations.AlterField(
            model_name='customer_order_model',
            name='phone_number',
            field=models.CharField(error_messages={'validators': 'Please enter correct Phone number'}, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
