# Generated by Django 3.0.3 on 2022-01-12 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20220111_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order_model',
            name='mail_id',
            field=models.CharField(error_messages={'validators': 'Please enter correct email id'}, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
