# Generated by Django 3.0.3 on 2022-01-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20220112_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order_model',
            name='mail_id',
            field=models.CharField(error_messages={'validators': 'Please enter correct email id'}, max_length=254),
        ),
    ]
