# Generated by Django 3.0.3 on 2022-01-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20220112_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order_model',
            name='mail_id',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer_order_model',
            name='phone_number',
            field=models.CharField(max_length=16),
        ),
    ]
