# Generated by Django 3.0.3 on 2021-02-20 08:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tyre_stockmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_name', models.CharField(max_length=50, unique=True)),
                ('number_of_tyres', models.PositiveIntegerField()),
                ('reorder_number', models.PositiveIntegerField()),
                ('date_refreshed', models.DateField(auto_now=True)),
                ('price', models.PositiveIntegerField()),
                ('commercial_vehicle_tyre', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='new_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=15)),
                ('quantity', models.PositiveIntegerField()),
                ('bought_from', models.CharField(max_length=30)),
                ('date_added', models.DateField(default=datetime.date(2021, 2, 20))),
                ('tyre_name_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tyre_stock.tyre_stockmodel')),
            ],
        ),
    ]
