# Generated by Django 3.0.3 on 2021-02-20 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tyre_stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_stock',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
