# Generated by Django 3.0.3 on 2022-01-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyre_stock', '0005_auto_20220111_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_stock',
            name='order_number',
        ),
    ]
